# prometheus.yml
global:
  scrape_interval: 15s  # Coletar métricas a cada 15 segundos
  evaluation_interval: 15s

scrape_configs:
  # Job para coletar métricas do Silver
  - job_name: 'silver_pipeline'
    static_configs:
      - targets: ['ingest:8000']  # Porta onde silver.py expõe métricas
        labels:
          service: 'silver'
          layer: 'processing'
  
  # Job para coletar métricas do MinIO
  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    bearer_token: "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoibWluaW9hZG1pbiIsImV4cCI6NDkyNjIyNDM5MH0.G8Nnprt7rStS7xvNKff8huu92ocvIPX7OGHl4Tlw1blXkQfk9-dz5hZGxP1rvmZ0uKVQh4vnJTTljtYizFdxSA"
    static_configs:
      - targets: ['minio:9000']
        labels:
          service: 'storage'
  